//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clients()
        {
            this.units = new HashSet<units>();
        }
    
        public int id { get; set; }
        public string client_name { get; set; }
        public string contact_name { get; set; }
        public string phone { get; set; }
        public string alternative_phone { get; set; }
        public Nullable<byte> client_type { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string alternative_email { get; set; }
        public int units_total { get; set; }
        public int user_id { get; set; }
    
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<units> units { get; set; }
    }
}
