//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoBus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spare_subcategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spare_subcategories()
        {
            this.spare_subclasses = new HashSet<spare_subclasses>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public int category_id { get; set; }
    
        public virtual spare_categories spare_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spare_subclasses> spare_subclasses { get; set; }
    }
}
